name = "lustre_dev_tools"
version = "1.6.0"
target = "erlang"
gleam = ">= 1.1.0"

description = "Lustre's official CLI and development tooling."
repository = { type = "github", user = "lustre-labs", repo = "dev-tools" }
licences = ["MIT"]

links = [
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["lustre_dev_tools", "lustre_dev_tools/*"]

[dependencies]
argv = "~> 1.0"
filepath = "~> 1.0"
fs = "~> 8.6"
gleam_community_ansi = "~> 1.4"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_erlang = "~> 0.25"
gleam_http = "~> 3.6"
gleam_httpc = "~> 3.0"
gleam_json = "~ 1.0 or ~> 2.0"
gleam_otp = "~> 0.10"
gleam_package_interface = "~> 1.0"
gleam_stdlib = "~> 0.34 or ~> 1.0"
glint = ">=1.0.0 and < 2.0.0"
glisten = ">= 6.0.0 and < 7.0.0"
mist = ">= 1.2.0 and < 4.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
spinner = "~> 1.1"
term_size = ">= 1.0.1 and < 2.0.0"
tom = ">= 1.0.1 and < 2.0.0"
wisp = "~> 1.1"
lustre = ">= 4.6.1 and < 5.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
