name = "lustre_dev_tools"
version = "1.2.1"
target = "erlang"
gleam = ">= 1.1.0"

description = "Lustre's official CLI and development tooling."
repository = { type = "github", user = "lustre-labs", repo = "dev-tools" }
licences = ["MIT"]

links = [
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["lustre_dev_tools", "lustre_dev_tools/*"]

[dependencies]
argv = "~> 1.0"
filepath = "~> 1.0"
gleam_community_ansi = "~> 1.4"
gleam_erlang = "~> 0.25"
gleam_http = "~> 3.6"
gleam_json = "~> 1.0"
gleam_otp = "~> 0.10"
gleam_package_interface = "~> 1.0"
gleam_stdlib = "~> 0.34 or ~> 1.0"
glint = "~> 0.18"
glisten = "~> 2.0"
mist = "~> 1.0"
simplifile = "~> 1.5"
spinner = "~> 1.1"
tom = "~> 0.3"
wisp = "~> 0.14"
fs = "~> 8.6"

[dev-dependencies]
gleeunit = "~> 1.0"
