name = "lustre_dev_tools"
version = "2.0.3"
target = "erlang"

description = "Lustre's official CLI and development tooling."
repository = { type = "github", user = "lustre-labs", repo = "dev-tools" }
licences = ["MIT"]

links = [
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["lustre_dev_tools/*"]

[documentation]
pages = [
    { title = "Static assets", path = "assets.html", source = "./pages/assets.md" },
    { title = "TOML reference", path = "toml-reference.html", source = "./pages/toml-reference.md" }
]


[dependencies]
argv = ">= 1.0.0 and < 2.0.0"
booklet = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
glint = ">= 1.0.0 and < 2.0.0"
group_registry = ">= 1.0.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
mist = ">= 5.0.3 and < 6.0.0"
polly = ">= 2.1.0 and < 3.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
tom = ">= 1.0.1 and < 3.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
